version: '3'
services:
  myapp:
    container_name: myapp
    tty: true
    build:
      context: ./myapp
      dockerfile: ./Dockerfile
    volumes:
      - ./myapp:/myapp
    ports:
      - 8081:8081
